name: Deploy to ECS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 986129559431.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t my-ecs-app .
      
      - name: Tag image for ECR
        run: docker tag my-ecs-app:latest 986129559431.dkr.ecr.us-east-1.amazonaws.com/my-ecs-app:latest

      - name: Push image to ECR
        run: docker push 986129559431.dkr.ecr.us-east-1.amazonaws.com/my-ecs-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster my-cluster \
            --service my-app \
            --force-new-deployment \
            --region us-east-1
